# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mresanto.mid
PackageVersion: 0.1.1

Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/mresanto/mid/releases/download/v0.1.1/mid.exe
    InstallerSha256: 7c00d971f4b7f721e56f369b8e4753868115cb8d7a70cf642705fad59bb88cbc
    Commands:
      - mid

ManifestType: installer
ManifestVersion: 1.12.0
Scope: user
ReleaseDate: 2026-08-30
